fix: swagger formData error
/node_modules/swagger2openapi/index.js:39
    let err = new S2OError(message);
              ^

S2OError: (Patchable) parameter.type is mandatory for non-body parameters
    at throwError (/node_modules/swagger2openapi/index.js:39:15)
    at processParameter (/node_modules/swagger2openapi/index.js:541:17)
    at processPaths (/node_modules/swagger2openapi/index.js:952:30)
    at main (/node_modules/swagger2openapi/index.js:1187:5)
    /node_modules/swagger2openapi/index.js:1556:13

PARAMS={
  in: 'formData',
  name: 'file',
  description: 'upload file',
  required: false,
  schema: { type: 'file' }
}